### PR TITLE
Remove clientExtensions and authenticatorExtensions from CollectedClientData

### LINKED ISSUE #804: Clarify how RP should verify extension outputs
@agl [notes][comment] in #803:

>The instructions say only that the RP should check that the echoed extensions are a subset, but it's unclear if that means that the values must be identical, esp in light of the fact that the RP is also instructed to check that the [authenticator extensions](https://w3c.github.io/webauthn/#dom-collectedclientdata-authenticatorextensions) are a subset, where it cannot check the values. If values aren't checked, a compromised origin context can still manipulate the contents of an extension.

I suggest we should

- clarify what exactly (extension IDs? values? etc) should be a subset of what;
- add a step to the RP operations instructing vaguely to verify that the extension outputs "are as expected".

I intend to self-assign this when the repo is unlocked.

[comment]: https://github.com/w3c/webauthn/issues/803#issuecomment-366296231

### PR DESCRIPTION
**Pull request by selfissued**
Fixes part of #803 
Fixes #804

***
<a href="https://pr-preview.s3.amazonaws.com/selfissued/webauthn/pull/811.html" title="Last updated on Feb 21, 2018, 10:25 PM GMT (8a3ea00)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/811/05335d4...selfissued:8a3ea00.html" title="Last updated on Feb 21, 2018, 10:25 PM GMT (8a3ea00)">Diff</a>

### CODE REVIEW

**Comment by emlun** [comment]
This solves part of #804, but not all of it. Specifically, this remains unresolved:

>- add a step to the RP operations instructing vaguely to verify that the extension outputs "are as expected".

**Comment by emlun** [comment]
I've submitted a PR into this one at https://github.com/selfissued/webauthn/pull/3 .

**Comment by nadalin** [comment]
@selfissued please review @emlun addtions

**Comment by selfissued** [comment]
I have added @emlun 's take on the verification step to the PR.

**Pull request merged**
