### PR TITLE
Sign counter alg 507 alternative: optional sig counter

### PR DESCRIPTION
**Pull request by rlin1**
This is the one with MSB=1 flagging it is not supported. MSB=0 means it is suported and included in the other bits.

***
[Preview](https://s3.amazonaws.com/pr-preview/w3c/webauthn/sign-counter-alg-507-alternative.html) | [Diff](https://s3.amazonaws.com/pr-preview/w3c/webauthn/089c10e...1a93e76.html)

### CODE REVIEW

**Comment by selfissued** [comment]
This would replace #539

**Comment by selfissued** [comment]
Fixes #507

**Comment by equalsJeffH** [comment]
on 4-oct-2017 webauthn call, @rlin1 is asserting that in Sydney last week (fido meeting) folks want to go with this PR and we will close pr #539

**Comment by equalsJeffH** [comment]
seems to need another merge-from-master

**Comment by ve7jtb** [comment]
Rolf did two solutions.  One with the counter fixed at 0 for non support of the counter and one with the MSB set to 1 to show non support of the counter.  I thought people were wanting the 0 option in Sydney.   Both work for me.    However I think the 0 option one had more work done on it.  In this I don't see a verification step if the MSB is 1, so may not be complete.

**Comment by jehrensvard** [comment]
I support Rolf's proposal.

It also gives us the option to use 0 as a "phantom" return value for MakeCredential calls with U2F devices. As we do not have a signature counter value for these, it seems sensible to return 0 then. Adding more potential use for the value 0 seems messy.

**Comment by rlin1** [comment]
regarding https://github.com/w3c/webauthn/pull/597#issuecomment-334604391
see line 2179 in index.bs:
              <dt>greater or equal to 0x80000000 (i.e. has MSB set to 1).</dt>

**Pull request closed without merging**
