### PR TITLE
reverting and restoring automation section et al...

### PR DESCRIPTION
**Pull request by equalsJeffH**
somehow I accidentally deleted @nsatragno's automation section when I merged-in the updates to `draft-hodges-webauthn-registries*`, sigh....  

hopefully this fixes it without messing anything else up....

NOTE: WE SHOULD NOT MAKE ANY MERGES TO MASTER UNTIL THIS IS RESOLVED!

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/pull/1340.html" title="Last updated on Nov 5, 2019, 11:51 PM UTC (e2ecccd)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/1340/28e8d9d...e2ecccd.html" title="Last updated on Nov 5, 2019, 11:51 PM UTC (e2ecccd)">Diff</a>

### CODE REVIEW

**Comment by equalsJeffH** [comment]
thx for tugging my sleeve @nsatragno !

Others: PLEASE REVIEW -- it seems this is restoring various other commits also, see https://pr-preview.s3.amazonaws.com/w3c/webauthn/1340/28e8d9d...e2ecccd.html

**Comment by equalsJeffH** [comment]
PLEASE: those nominated to review, please do so (and do so carefully)...   upon closer inspection, it seems that I somehow removed the commits in the range [976391d..b5c4001], see this `git history` excerpt (master branch): 
```
* | | | a55edbf 2019-10-18 | Align with RFC8288, update .txt & .html to be actual rendered versions of .xml (#1329) [=JeffH]
| |_|/  
|/| |   
* | | b5c4001 2019-10-17 | Timeout considerations (#1317) [Akshay Kumar]
* | | 6b03c65 2019-10-17 | revise draft-hodges-webauthn-registries per AD review and initiate work on rev -03 (#1322) [=JeffH]
|/ /  
* | 36fe4ed 2019-10-09 | Add note about use of floating point in extensions passed through that clients do not recognize (#1307) [Mike Jones]
* |   2773c49 2019-10-09 | Merge pull request #1312 from w3c/issue-1309-clarify-rp-server [Emil Lundberg]
|\ \  
| * | 4d16a31 2019-10-07 | Clarify that RP is split into server and script (origin/issue-1309-clarify-rp-server) [Emil Lundberg]
| |/  
* |   72e2f47 2019-10-09 | Merge pull request #1299 from w3c/issue-1188-rp-transports [Emil Lundberg]
|\ \  
| * | 5f3f988 2019-09-11 | Address @equalsJeffH's review comments (origin/issue-1188-rp-transports) [Emil Lundberg]
| * | f599d9b 2019-09-11 | Mention getTransports() in PublicKeyCredentialDescriptor definition [Emil Lundberg]
| * | 5781243 2019-09-11 | Recommend RPs to store transport hints [Emil Lundberg]
| * | 24ecf51 2019-09-11 | Formalise beginning of RP ops [Emil Lundberg]
* | | c7e44f6 2019-10-09 | Add privacy considerations about credential IDs (#1250) [Emil Lundberg]
* | | 00114e9 2019-10-09 | ack Nina (automation/webdriver) (#1310) [=JeffH]
| |/  
|/|   
* |   976391d 2019-10-02 | Merge pull request #1256 from nsatragno/automation [Adam Langley]
```
It seems merging this branch will restore these commits, but please do verify that this assertion is correct. Much thanks to @nsatragno for noticing and helping with restoration.

**Comment by emlun** [comment]
Looks like the offending commit is a55edbf89206dc329d160abf7e9eb67e8303e030 which is a squash of PR #1329 whose HEAD at the time was commit 6bb9b19a4359a79b5555e3298218ff7ec66f59c0. I managed to reconstruct the deleted branch, and those two commits have identical contents.

The deletion happened in the merge commit a9bff8be9d472813462dcf447da924171295ae99 in PR #1329. The PR originally branched from commit 2b435a7, and a9bff8be9d472813462dcf447da924171295ae99 merged commit b5c4001 from master. I think what happened is that while resolving the merge conflicts in the `draft-hodges-webauthn-registries.*` files, @equalsJeffH inadvertently removed the `index.bs` changes from staging, which meant the merge commit reverted them.

The heads that have been merged into master after a55edbf89206dc329d160abf7e9eb67e8303e030 are a1d4e06 (squash of PR #1328), 562cafb, f67c44b, 101146b, 35c25de, b58f3a3, 243d8f7, 235385c (branched after a55edb), 428bf82 (squash #1316), 97411db (squash #1323), 88468ca (squash #1324), a14e11d (branched after), 03f8406 (squash #1335), dbcf596 (branched after), and e48cb03 (squash #1334).

I've reconstructed a new copy of the merge commit a9bff8be9d472813462dcf447da924171295ae99 without the accidental revert, and a new master branch merging that followed by the other heads. I'm pleased to say the diff between the reconstructed master and the head of this PR is the empty diff! :smile: I pushed the reconstructed master as `emlun-reconstructed-master` in case anyone wants to take a look.

**Comment by equalsJeffH** [comment]
thanks @emlun for [the detailed analysis/explanation](https://github.com/w3c/webauthn/pull/1340#issuecomment-550462834)! (I had not yet seen it during the webauthn call earlier today)!  

So, in master branch, I've diffed the spec rendered at the most recent commit 8927216 from the rendered spec at commit 976391d, i.e.:  [8927216..976391d], and gone through the diff and matched up new/revised text with the commits listed by `git hist` in that interval, and it looks like everthing is there in the present most-recent state in master branch, in `index.bs` -- yay!

HOWEVER, it seems that we've overlooked restoring the revised .svg file that @agl commited & merged-to-master for [figure 6](https://w3c.github.io/webauthn/#fig-stringTruncation)  -- the file being: `images/string-truncation.svg`.  see the potentially-relevant commit `428bf82 2019-10-29 | Truncate strings for authenticators where needed. (#1316) [Adam Langley]`

@agl likely has this file on his machine and perhaps it's easiest to just open a new PR to update said file (rather than mess around trying to restore it using git-magic) ?

ANYWAY, we shouldn't roll an updated working draft until we've fixed this, please.

**Comment by emlun** [comment]
Isn't that the revised version of the image? To me it looks the same as the one in https://github.com/w3c/webauthn/pull/1316#issuecomment-543466526, and both 428bf82 and master have the same blob for that file:

```
$ git ls-tree 428bf82 -- images/string-truncation.svg
100644 blob 54197159ae623ad5114d6c2b85e15824cfca1df7    images/string-truncation.svg
$ git ls-tree origin/master -- images/string-truncation.svg
100644 blob 54197159ae623ad5114d6c2b85e15824cfca1df7    images/string-truncation.svg
```

**Comment by agl** [comment]
The `string-truncation.svg` currently in master (8927216e4b1c8eb9ead1b796f084a6d8f152dd6e) matches what I have on disk (SHA-256 96ff3e51827256f413593ee187c25f40f6d58d2a2c930bddf47ff942320c7d71).

**Comment by equalsJeffH** [comment]
Hm, thanks for checking....  very innaresting -- so yesterday, when visually reviewing the latest rendered spec&mdash;i.e. https://w3c.github.io/webauthn/#fig-stringTruncation &mdash;in Chrome, the latter image renders (for me anyway) with the vertical dashed lines miss-aligned.  I recalled that @agl had committed an updated image (the one pointed to here https://github.com/w3c/webauthn/pull/1316#issuecomment-543466526) and so was suprised when the image in the spec in chrome renders mis-aligned (and still does this morning).  

In firefox (on glinux and windows) it renders fine (is mis-aligned on both platforms for me)

**Pull request merged**
