### PR TITLE
Rename MakePublicKeyCredentialOptions to PublicKeyCredentialCreateOptions

### LINKED ISSUE #773: Rename MakePublicKeyCredentialOptions?
I realize this is late in the game, but can we rename `MakePublicKeyCredentialOptions` to `PublicKeyCredentialCreateOptions` so that it matches the naming conventions of [other APIs](https://developer.mozilla.org/en-US/docs/Web/API)? It's just a dictionary (not an interface), so hopefully it would be an easy change...

### PR DESCRIPTION
**Pull request by selfissued**
Fixes #773

***
<a href="https://pr-preview.s3.amazonaws.com/selfissued/webauthn/pull/779.html" title="Last updated on Feb 7, 2018, 6:10 PM GMT (5047625)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/779/f13e030...selfissued:5047625.html" title="Last updated on Feb 7, 2018, 6:10 PM GMT (5047625)">Diff</a>

### CODE REVIEW

**Comment by emlun** [comment]
I think some of the browser people should probably review this too. @akshayku @agl @jcjones?

**Comment by agl** [comment]
I don't believe that is has an observable impact thus I don't think any special browser input is needed here. The new name seems to fit better with with web APIs, so looks good to me.

**Comment by nadalin** [comment]
@selfissued So can you merge this based upon AGL input ?

**Comment by selfissued** [comment]
I don't understand what is being requested in the comment. What is the specific change that you are suggesting?

**Comment by emlun** [comment]
I suggest changing `Create` to `Creation`.

**Comment by selfissued** [comment]
Fine by me

**Pull request merged**
