### PR TITLE
Correct Android Key attestation verification procedure

### LINKED ISSUE #599: Need to fix android key attestation verification procedure
#546 PR fixes the android attestation generation issue.
The resolution is to change the signing procedure to handle properly android key attestation. But the verification procedure does not reflect these modification.
So, verification procedure should be fixed.
Followings are need to be fixed.
> The value of the attestationChallenge field is identical to the concatenation of authenticatorData and clientDataHash.

In stead,

> The value of the attestationChallenge field is identical to clientDataHash.

### PR DESCRIPTION
**Pull request by arnar**
Fixes #599

***
<a href="https://pr-preview.s3.amazonaws.com/arnar/webauthn/pull/717.html" title="Last updated on Dec 8, 2017, 12:59 AM GMT (10796c0)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/717/33ac796...arnar:10796c0.html" title="Last updated on Dec 8, 2017, 12:59 AM GMT (10796c0)">Diff</a>

### CODE REVIEW

**Comment by rlin1** [comment]
I propose setting milstone to CR

**Comment by equalsJeffH** [comment]
issue #599 is CR so setting this as that

**Comment by equalsJeffH** [comment]
Reviewed, LGTM!

**Comment by equalsJeffH** [comment]
decided on 2017-Dec-20 call to merge this.

**Pull request merged**
