### PR TITLE
Jeffh editorial cleanups4

### PR DESCRIPTION
**Pull request by equalsJeffH**
Please do not merge as yet -- will continue to add to this as we work on WD-04

### CODE REVIEW

**Comment by equalsJeffH** [comment]
Please do not merge as yet -- will continue to add to this as we work on WD-04

**Comment by equalsJeffH** [comment]
thx to @rlin1 for fixing my erroneous tagging :)

**Comment by leshi** [comment]
Read through this.  In general LGTM, but might need to re-sync.

**Comment by equalsJeffH** [comment]
thx @leshi. by "need to re-sync" I assume @leshi means to merge-with-master, with brings in the recent "attachment" additions, and resolve conflicts.  that's now done with commit https://github.com/w3c/webauthn/pull/306/commits/a479fed82d2c8bb762f70cd847b15841e813a074.  How's it look?

**Comment by equalsJeffH** [comment]
On the last call, the overall sentiment was to go ahead and merge this PR #306 rather than keeping it open and adding further to it.  Would be good to get some further reviews, thx.

**Comment by equalsJeffH** [comment]
AFAICT it is ready to land.

**Comment by equalsJeffH** [comment]
thx @jcjones

**Pull request merged**
