### PR TITLE
fix #792: use utf 8 decode directly

### LINKED ISSUE #792: reference "UTF-8 decode" directly rather than "parse JSON from bytes"
we recently insterted:
> Let |C|, the [=client data=] claimed as collected during the credential creation, be the result of [=parse JSON from bytes|parsing JSON from the bytes=] in <code>|response|.{{AuthenticatorResponse/clientDataJSON}}</code>.

However, this is most likely invoked RP-server-side, and is JS-specific (as we discussed).  I'm thinking we can make it implementation-non-specific by referencing https://encoding.spec.whatwg.org/#utf-8-decode, which is what [parse JSON from bytes](https://infra.spec.whatwg.org/#parse-json-from-bytes)  does in any case, and indicating that any impl is fine as long as the end results are the same as [UTF-8 decode](https://encoding.spec.whatwg.org/#utf-8-decode) provides.

See PR #793 

also fixes #712

### PR DESCRIPTION
**Pull request by equalsJeffH**
fixes #792

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/pull/793.html" title="Last updated on Feb 10, 2018, 7:08 PM GMT (07a1c28)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/793/2bc4c05...07a1c28.html" title="Last updated on Feb 10, 2018, 7:08 PM GMT (07a1c28)">Diff</a>

### CODE REVIEW

**Comment by equalsJeffH** [comment]
agreed, added explicit JSON  parsing step

**Comment by emlun** [comment]
The assertion verification algorithm might need this change, too.

**Comment by nadalin** [comment]
@selfissued @akshayku Please review

**Comment by equalsJeffH** [comment]
@emlun 
> there are probably a few hard-coded step references after this that need to be updated.

doh!  thx!

**Comment by equalsJeffH** [comment]
@emlun 
> The assertion verification algorithm might need this change, too.

indeed, it did, done.  double-checked inter-step references.  fixed up denotation of |C| as client data (rather than the intermediate |JSONtext|.

**Comment by equalsJeffH** [comment]
would be good to get a careful double-double check on this to see if I messed anything else up thx. :)

**Comment by nadalin** [comment]
@equalsJeffH Please merge

**Comment by nadalin** [comment]
@selfissued can you merge as we want to generate a document

**Pull request merged**
