### PR TITLE
#420: Add note on why authenticator attachment is used only in create()

### PR DESCRIPTION
**Pull request by emlun**
See #420.

### CODE REVIEW

**Comment by equalsJeffH** [comment]
Reviewed: https://github.com/w3c/webauthn/pull/708#pullrequestreview-81634828
LGTM. Thanks @emlun!

**Comment by agl** [comment]
(I was asked to review this during last week's call. Looks good to me.)

**Comment by akshayku** [comment]
Can someone explain to me how an RP who only wants to talk to, lets say, platform authenticators can achieve this without attachment option in assertion?

**Comment by equalsJeffH** [comment]
discussed @akshayku's comment on the 20-Dec-2017 call and obtained consensus to merge this.

**Pull request merged**
