### PR TITLE
Make hashAlg a "recognized algorithm name".

### PR DESCRIPTION
**Pull request by jyasskin**
Fixes the hashAlg part of #273.

### CODE REVIEW

**Comment by jyasskin** [comment]
@vijaybh @selfissued I don't have any problem with using shorter strings for these algorithms, but we do need to be clear what set of strings are valid.

I believe it was always incorrect to add SHA-256, etc. to the IANA JWS registry because S256, etc. had a different set of inputs than HS256, etc., and there was nothing in the registry to distinguish the two kinds of names. If you still want to use shorter names, we'll need to make a new registry.

**Comment by vijaybh** [comment]
LGTM

I will note there is currently no "recognized algorithm name" corresponding to SM3 but maybe that should be fixed elsewhere by someone defining a new WebCrypto algorithm.

**Comment by jyasskin** [comment]
Yeah, if you need SM3 for this spec, it'd be reasonable to define it here, in the same style as the other WebCrypto algorithms. We should accompany doing that with a WebCrypto issue so they know to upstream it when they have a chance.

(I'm assuming this spec has a good reason for adding a new hash algorithm.)

**Comment by equalsJeffH** [comment]
wrt SM3, fyi/fwiw, it is there to support deployment in China (e.g., we added refs to the latter alg as well as a couple of other Chinese-standardized crypto algs to [the FIDO registry](https://fidoalliance.org/specs/fido-uaf-v1.1-id-20170202/fido-registry-v1.1-id-20170202.html) when defining a bit flag name for the Chinese SM2 elliptic curve based signature algorithm: ALG_SIGN_SM2_SM3).

though, it seems to me that defining "recognized alg names" for Chinese-approved crypto algs is a W3C policy/political decision beyond this working group's remit, and so we probably should not attempt to define it in this spec.

**Comment by selfissued** [comment]
I am OK with this pull request.

**Pull request merged**
