### PR TITLE
Recommend minimal basic attestation batches

### LINKED ISSUE #1127: Attestation privacy advice creates large scale security risks
> A WebAuthn authenticator manufacturer may choose to ship all of their authenticators with the same (or a fixed number of) attestation key(s) (called Basic Attestation). This will anonymize the user at the risk of not being able to revoke a particular attestation key if its private key is compromised.

I understand that from privacy perspective, this is a really good advice. However it is really bad security approach. Imagine manufacturer that releases ten million devices. One's device attestation key is compromised, so entire ten million devices must be marked as revoked. This is why it's called "batch" and not "manufacturer", because certificate and keypair are generated per "batch" of keys, so quantifiably limited. Right now our policy is 1 attestation keypair per 100k. That is deemed sufficient to mitigate privacy risks, while enabling effective security scaling of the attestation.

> [UAFProtocol] requires that at least 100,000 authenticator devices share the same attestation certificate in order to produce sufficiently large groups. This may serve as guidance about suitable batch sizes.

This is FIDO's policy regarding of the protocol. U2F/FIDO2/UAF are all have the same mandatory requirements.

### PR DESCRIPTION
**Pull request by emlun**
Fixes #1127.

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/pull/1141.html" title="Last updated on Jan 18, 2019, 6:05 PM UTC (a81b7e7)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/1141/c610a95...a81b7e7.html" title="Last updated on Jan 18, 2019, 6:05 PM UTC (a81b7e7)">Diff</a>

### CODE REVIEW

**Comment by emlun** [comment]
Ping @herrjemand

**Comment by herrjemand** [comment]
LGTM! @emlun

**Comment by agl** [comment]
LGTM

**Comment by equalsJeffH** [comment]
purely editorial  with five unqualified review approvals -- suggest we just merge this now.

**Comment by emlun** [comment]
So merge immediately after #1156?

**Pull request merged**
