### PR TITLE
Fix typo

### PR DESCRIPTION
**Pull request by quaff**
though should be through

***
<a href="https://pr-preview.s3.amazonaws.com/quaff/webauthn/pull/1341.html" title="Last updated on Nov 8, 2019, 9:12 AM UTC (c363e4a)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/1341/8927216...quaff:c363e4a.html" title="Last updated on Nov 8, 2019, 9:12 AM UTC (c363e4a)">Diff</a>

### CODE REVIEW

**Comment by jcjones** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by jcjones** [comment]
Marked non-substantive per https://www.w3.org/2019/Process-20190301/#substantive-change section 6.2.5 bullet 2, that this is fits the bullet **Corrections that do not affect conformance**.

**Comment by emlun** [comment]
So... I guess that means we're clear to merge?

**Comment by nadalin** [comment]
@emlun Yes clear to merge

**Pull request merged**
