### PR TITLE
update bikeshed cache

### PR DESCRIPTION
**Pull request by equalsJeffH**
hope I did it correctly, my bikeshed install is not the same as that assumed in the the instructions in README.md

Here's what I did:
```
pip3 install --upgrade bikeshed && bikeshed update  # update bikeshed program & data when pip3 has been used for install

cd <local webauthn repo clone>
git remote update
git co master
git pull
git co -b <new branch name>

cat update-bikeshed-cache.sh    # to see what it does...

# manually do the two copy operations that update-bikeshed-cache.sh does, using appropriate paths...
/bin/cp -a -f ~/.local/lib/python3.8/site-packages/bikeshed/spec-data/* ./.spec-data/
/bin/cp -a -f ~/.local/lib/python3.8/site-packages/bikeshed/boilerplate/webauthn/* ./.bikeshed-include/

git add .spec-data/ .bikeshed-include/
git commit
git push origin <new branch name>
```

### CODE REVIEW

**Review by wseltzer — CHANGES_REQUESTED** [review]
Looking at the initial files, there seems to be a reversion in the status boilerplate, e.g. switching https links to http and losing the dated Patent Policy links. I think we'll need a more granular approach.

**Comment by equalsJeffH** [comment]
> ...there seems to be a reversion in the status boilerplate...

I wonder how my `~/.local/lib/python3.8/site-packages/bikeshed/boilerplate/webauthn/*` files got (apparently) polluted :(

So, rather than my trying to rescue this PR and possibly making things worse, perhaps someone other than me ought to attempt to fix the problem, where the problem is that the spec build data and possibly machinery are (apparently) out-of-date.

**Comment by wseltzer** [comment]
I think I need to send some changes back to bikeshed for the webauthn-specific includes. I'll try a different PR on the other files.

**Comment by sideshowbarker** [comment]
Superseded by #1553

**Comment by equalsJeffH** [comment]
thanks @wseltzer & @sideshowbarker !!

**Pull request closed without merging**
