### PR TITLE
In safetynet attestation "nonce" is base64, not base64url

### PR DESCRIPTION
**Pull request by herrjemand**
cc @christiaanbrand @kpaulh

***
<a href="https://pr-preview.s3.amazonaws.com/herrjemand/webauthn/pull/1093.html" title="Last updated on Oct 3, 2018, 8:56 AM GMT (7b487ff)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/1093/2056fee...herrjemand:7b487ff.html" title="Last updated on Oct 3, 2018, 8:56 AM GMT (7b487ff)">Diff</a>

### CODE REVIEW

**Comment by Kieun** [comment]
Indeed Safetynet attestation from Android Chrome browser has base64 encoded nonce value.

**Comment by equalsJeffH** [comment]
thanks Yuriy, tho it's preferable that there be a corresponding open issue (if there is, i could not find one when searching issues for Safetynet), and also it'd be best if the issue links to where this is stated in the Android Safetynet docs.  thanks again!

**Comment by herrjemand** [comment]
Ref: #968

**Comment by herrjemand** [comment]
https://gist.github.com/herrjemand/62f03f5695a2749031c933d00cbfba07

**Pull request merged**
