### PR TITLE
Refer to options for the user verification check

### PR DESCRIPTION
**Pull request by infinisil**
Fixes https://github.com/w3c/webauthn/issues/1699, see also the discussion in https://github.com/w3c/webauthn/pull/1704

Ping @emlun @sbweeden

***
<a href="https://pr-preview.s3.amazonaws.com/tweag/w3c-webauthn/pull/1718.html" title="Last updated on Apr 7, 2022, 1:44 PM UTC (5d42923)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/1718/331188b...tweag:5d42923.html" title="Last updated on Apr 7, 2022, 1:44 PM UTC (5d42923)">Diff</a>

### CODE REVIEW

**Comment by infinisil** [comment]
@agl Ah I see now, so a potential attack here is a non-conformant client, pretending that the authenticator doesn't support user verification, when it really does, in case of `userVerification` set to `"preferred"`. A conformant client would always ask for user verification in such a case, as specified in the client's [Create](https://www.w3.org/TR/webauthn-2/#sctn-createCredential) and [Get](https://www.w3.org/TR/webauthn-2/#sctn-getAssertion) specifications.

In this case I believe the description of [`"preferred"`](https://www.w3.org/TR/webauthn-2/#dom-userverificationrequirement-preferred) should be adjusted, because it currently reads:

> `preferred`: This value indicates that the [Relying Party](https://www.w3.org/TR/webauthn-2/#relying-party) prefers [user verification](https://www.w3.org/TR/webauthn-2/#user-verification) for the operation if possible, but will not fail the operation if the response does not have the [UV](https://www.w3.org/TR/webauthn-2/#uv) [flag](https://www.w3.org/TR/webauthn-2/#flags) set.

I believe the `will not fail` should be changed to `may not fail`. A mention of client policy would also be good here.

Additionally I believe that the [Registering a New Credential](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#sctn-registering-a-new-credential) and [Verifying an Authentication Assertion](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#sctn-verifying-assertion) relying party operations should be expanded with a step to determine whether user verification is _effectively_ required (similar to the `Create`/`Get` operations). This would look something like this:

> 14. Let `userVerification` be the effective user verification requirement for credential creation as follows:
>
>     If `options.userVerification`
>     - is set to `"required"`: Let `userVerification` be `true`
>     - is set to `"preferred"`: Let `userVerification` be determined by client policy, taking into account further information gathered from the response [be more specific, what information can the relying party use here?]
>     - is set to `"discouraged"`: Let `userVerification` be `false`
> 15. If `userVerification` is `true`, verify that the [User Verified](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#concept-user-verified) bit of the [flags](https://www.w3.org/TR/2021/REC-webauthn-2-20210408/#flags) in authData is set.

This also makes it clear that it's relying party policy, but only in the `"preferred"` case.

If that sounds okay then I can propose a PR.

**Comment by Firstyear** [comment]
> This also makes it clear that it's relying party policy, but only in the `"preferred"` case.

There is no text in the RP section about what do do in the "I asked for preferred but got back UV=false" case. Only "UV=true is verify when required was went".

So this section also needs to be amended to include that if the RP asks for preferred, they can make a choice based on RP data to verify the UV bit.

**Comment by emlun** [comment]
@agl's comment above still reflects the WG's position on this - the proposed text is too specific and doesn't capture that an RP may have many reasons to require UV or not. We think the current spec text is appropriately abstract here.

**Comment by Firstyear** [comment]
I think you mis-understand the issue, and the fact that there are literally CVE's that exist because of this defect. It has affected Azure AD, Okta, nextcloud and more. UV preferred is misleading because RP's do not validate it when requested, and RP's *believe* that it is required.

There is a blindingly obvious gap in this specification for "what happens when I ask for UV preferred" during registration and authentication.

**Comment by emlun** [comment]
That is a different issue which has been discussed and closed in #1618.

**Comment by Firstyear** [comment]
Sure, but you still never resolved the issue either in #1618.

**Comment by infinisil** [comment]
I'm a bit disappointed by W3C regarding this.
- I saw something in the specification that I didn't understand how to implement in a library, so I opened [an issue](https://github.com/w3c/webauthn/issues/1699) asking for clarification.
- A small [PR](https://github.com/w3c/webauthn/pull/1704) with a supposed fix was opened, however I [clearly stated](https://github.com/w3c/webauthn/pull/1704#issuecomment-1050043574) that it still didn't make any sense to me, but the PR was merged without addressing my points and the issue was deemed resolved.
- I was told that I can propose another PR, which I did here. While the changes themselves aren't that important, I finally [understood](https://github.com/w3c/webauthn/pull/1718#issuecomment-1128023604) the real problem with the specification and made some clear suggestions for how it could be improved.
- However again, it seems like the WG doesn't deem my concerns here valid and closes the PR, considering the issue resolved. At this point the specification is still as unclear as it was from the beginning, and I'm glad for @Firstyear backing me up here.

So what should I do here? Leave it be and hope that everybody in the future figures out what the specification means themselves? Or should I try to open another PR, hoping that my concerns are taken seriously then?

**Comment by emlun** [comment]
I'm sorry we let you down @infinisil. Opening issues for things I didn't understand was how I, too, got involved with the WG, and I want that opportunity to be open to you too.

As we've said, we think the language proposed here is too specific, but your and @Firstyear's input have given me some other ideas for how we could improve this. I've outlined some of these thoughts in https://github.com/w3c/webauthn/issues/1510#issuecomment-1151576857. In principle I wouldn't mind some help drafting it, but it will likely also tie into #1556 and #1740 - these all relate to and/or would benefit from a more formalized representation of a "credential record" on the server side - so it's going to be a bit tricky to get it all to fit together and to work within Bikeshed. But you (and @Firstyear) are welcome to give it a try if you want, though I understand if you feel disheartened. I've pushed some half-baked thoughs on a [branch in my fork](https://github.com/emlun/webauthn/tree/wip/credential-record) where you can at least see the general direction I'm going with some of it. But note that it's all very experimental, perhaps none of it will make it into the spec in the end.

**Comment by Firstyear** [comment]
> though I understand if you feel disheartened.

I certainly feel this, since it has been a bit more than a year (especially around this issue), and I feel that the concerns I have an as RP aren't really taken seriously - from both a public RP viewpoint, and an enterprise one I can see lots of rough patches that RP's will run into. But I'm glad to see some of these things start to change, because I do want to contribute, and I do care about these things.

**Pull request closed without merging**
