### PR TITLE
Add example of different RP ID and AppID

### PR DESCRIPTION
**Pull request by emlun**
Clarification attempt in response to review: https://github.com/w3c/webauthn/pull/1118#pullrequestreview-200306589

***
<a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/pull/1165.html" title="Last updated on Mar 5, 2019, 6:40 AM UTC (6ff9820)">Preview</a> | <a href="https://pr-preview.s3.amazonaws.com/w3c/webauthn/1165/dafc308...6ff9820.html" title="Last updated on Mar 5, 2019, 6:40 AM UTC (6ff9820)">Diff</a>

### CODE REVIEW

**Comment by emlun** [comment]
Thanks @leshi!

**Comment by manger** [comment]
Would https://accounts.example.com/appId be a better sample AppID than https://accounts.example.com?
Both might be valid, but the latter makes it awkward to serve a TrustedFacetList from that address, which is necessary to authorise mobile apps and sibling domains to share the credentials.

**Comment by equalsJeffH** [comment]
Hey @emlun @agl -- AFAiCT this example text did **not** land in the master branch and thus is not contained in the Note (PR #1118) in https://www.w3.org/TR/webauthn-2/#sctn-appid-extension -- Am I hallucinating or not?

**Comment by emlun** [comment]
Yep, looks like the `appid-note` branch of PR #1118 was merged into master as commit 11126e8, and PR #1165 (this one) was merged into the `appid-note` branch after that as commit 379f7ab. I'll merge the branch into master again.

**Comment by emlun** [comment]
Oh...
```
remote: error: GH006: Protected branch update failed for refs/heads/master.
remote: error: At least 1 approving review is required by reviewers with write access.
```

I guess I'll just open a new PR to re-merge this. Thanks @equalsJeffH, good catch!

**Pull request merged**
