### PR TITLE
Fix typo in Figure 1

### LINKED ISSUE #1084: Typo in Figure 1?
In [Figure 1 Registration Flow](https://www.w3.org/TR/2018/CR-webauthn-20180807/#fig-registration), `PublicKeyCredentialCreateOptions` seems to be a typo.

Maybe it means `PublicKeyCredentialCreationOptions`?

### PR DESCRIPTION
**Pull request by emlun**
This fixes #1084. I also noticed a piece of the last letter in "AuthenticatorAttestationResponse" gets cropped, so I pulled that a little bit to the left too.

### CODE REVIEW

**Comment by emlun** [comment]
Merge this?

**Comment by emlun** [comment]
Merge this?

**Comment by rlin1** [comment]
LGTM

**Comment by rlin1** [comment]
LGTM

**Comment by emlun** [comment]
Merge this?

**Pull request merged**
