### PR TITLE
Fixed incorrect field size that makes all letters to overlap each other

### PR DESCRIPTION
**Pull request by herrjemand**

### CODE REVIEW

**Comment by herrjemand** [comment]
screenshot 2018-04-30 14 35 42

Fixed this

**Comment by equalsJeffH** [comment]
@nadalin @samweiler would someone having appropriate authz please mark this as "non-substantive" ?

**Comment by equalsJeffH** [comment]
wrt the travis-ci failing, see https://github.com/w3c/webauthn/pull/884#issuecomment-385520285

**Comment by equalsJeffH** [comment]
let's include this in the PR (proposed rec) milestone

**Comment by samuelweiler** [comment]
Marked as non substantive for IPR from ash-nazg.

**Comment by samuelweiler** [comment]
Marked as non-substantive re: IPR concerns. @herrjemand: thank you!

**Comment by equalsJeffH** [comment]
merge from upstream/master ought to fix the breaking build

**Comment by nadalin** [comment]
@herrjemand please fix and then merge as Jeff indicates

**Pull request merged**
